pull_request_rules:
  - name: automatic merge dependabot PRs
    conditions:
      - author=dependabot-preview[bot]
      - status-success=lint-build
      - files=requirements.txt
    actions:
      merge:
        method: merge
