on:
  push:
    branches:
      - master

jobs:
  lint-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: wrboyce/python-lint-action@v1.0.0
      - uses: actions/setup-python@v1
      - name: Install
        run: pip install -r requirements.txt
      - name: Build
        run: make html
      - name: Deploy
        run: make s3_upload
