on: pull_request

jobs:
  lint-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: wrboyce/python-lint-action@v1.0.0
      - uses: actions/setup-python@v1
      - name: Install
        run: pip install -r requirements.txt
      - name: Build
        run: make html

  docker-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
          - linux/arm/v7
    steps:
      - name: Setup Docker
        run: docker buildx create --name builder --use
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
      - name: Build Image
        run: make DOCKER_PLATFORMS=${matrix.platform} build
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
