on: pull_request

jobs:
  lint-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: wrboyce/python-lint-action@master
      - uses: actions/setup-python@v1
      - name: Install
        run: pip install -r requirements.txt
      - name: Build
        run: make html
